/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.pkgfinal;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class IniciarNuevoJuego extends javax.swing.JDialog {

    public int num;
    public Board padre;

    /**
     * Creates new form IniciarNuevoJuego
     */
    public IniciarNuevoJuego(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        jLabel4.setVisible(false);
        sizeBoard.setVisible(false);
        padre = (Board) parent;
        sizeBoard.setTransferHandler(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeroJugadores = new javax.swing.ButtonGroup();
        tamanoTablero = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        onePlayer = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        twoPlayers = new javax.swing.JRadioButton();
        predet = new javax.swing.JRadioButton();
        custom = new javax.swing.JRadioButton();
        sizeBoard = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        startGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Seleccione el modo de juego");

        numeroJugadores.add(onePlayer);
        onePlayer.setText("Un jugador");

        jLabel2.setText("Número de jugadores");

        jLabel3.setText("Tamaño del tablero");

        numeroJugadores.add(twoPlayers);
        twoPlayers.setText("Dos jugadores");

        tamanoTablero.add(predet);
        predet.setText("Predeterminado");
        predet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                predetMouseClicked(evt);
            }
        });

        tamanoTablero.add(custom);
        custom.setText("Personalizado");
        custom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customMouseClicked(evt);
            }
        });

        sizeBoard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sizeBoardKeyTyped(evt);
            }
        });

        jLabel4.setText("Ingrese número de casillas");

        startGame.setText("Iniciar Juego");
        startGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(twoPlayers)
                                    .addComponent(onePlayer))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(predet)
                                    .addComponent(jLabel3)
                                    .addComponent(custom)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(sizeBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(startGame)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onePlayer)
                    .addComponent(predet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twoPlayers)
                    .addComponent(custom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startGame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameActionPerformed
        // TODO add your handling code here:
        if (predet.isSelected()) {
            num = 30;
            if (onePlayer.isSelected()) {
                padre.singleplayer(num);
                this.dispose();
            } else if (twoPlayers.isSelected()) {
                padre.multiplayer(num);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Por favor seleccione una de las opciones para el número de jugadores");
            }
        } else if (custom.isSelected()) {
            if ("".equals(sizeBoard.getText())) {
                JOptionPane.showMessageDialog(null, "Introduzca algún número antes de dar click en el botón.");
            } else {
                num = Integer.parseInt(sizeBoard.getText());
                if (num < 5) {
                    JOptionPane.showMessageDialog(null, "Por favor, introduzca un tamaño de al menos 5 unidades.");
                } else {
                    if (onePlayer.isSelected()) {
                        padre.singleplayer(num);
                        this.dispose();
                    } else if (twoPlayers.isSelected()) {
                        padre.multiplayer(num);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Por favor seleccione una de las opciones para el número de jugadores");
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione una de las opciones para el tamaño del tablero");
        }
    }//GEN-LAST:event_startGameActionPerformed

    private void customMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customMouseClicked
        // TODO add your handling code here:
        sizeBoard.setVisible(true);
        jLabel4.setVisible(true);
    }//GEN-LAST:event_customMouseClicked

    private void predetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_predetMouseClicked
        // TODO add your handling code here:
        sizeBoard.setVisible(false);
        jLabel4.setVisible(false);
    }//GEN-LAST:event_predetMouseClicked

    private void sizeBoardKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sizeBoardKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_sizeBoardKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarNuevoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarNuevoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarNuevoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarNuevoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IniciarNuevoJuego dialog = new IniciarNuevoJuego(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton custom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.ButtonGroup numeroJugadores;
    private javax.swing.JRadioButton onePlayer;
    private javax.swing.JRadioButton predet;
    private javax.swing.JTextField sizeBoard;
    private javax.swing.JButton startGame;
    private javax.swing.ButtonGroup tamanoTablero;
    private javax.swing.JRadioButton twoPlayers;
    // End of variables declaration//GEN-END:variables
}
